jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
#      Python35:
#        python.version: '3.5'
#      Python36:
#        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip setuptools && pip install poetry
    displayName: 'Install dependencies'

  - script: |
      poetry install pytest
      poetry run pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

#- job: 'Publish'
#  dependsOn: 'Test'
#  pool:
#    vmImage: 'Ubuntu 16.04'
#
#  steps:
#  - task: UsePythonVersion@0
#    inputs:
#      versionSpec: '3.x'
#      architecture: 'x64'
#
#  - script: python setup.py sdist
#    displayName: 'Build sdist'
